
# Diccionario de frases de referencia adaptadas a Magic: The Gathering
effect_references = {
    "gain life": [
        "gain life",
        "recover life",
        "increase your life total",
    ],
    "lose life": [
        "lose life",
        "lose amount of lives",
        "you lose life",
        "reduce your life total",
        "lose 2 life",
        "lose any amount of life"
    ],
    "draw cards": [
        "draw cards",
        "draw a card",
        "draw your hand",
        "search your library for a",
        "search your graveyard for a",
        "search your deck for a",
        "draw two cards",
        "draw until you have",
    ],
    "put into play": [
        "put it onto the battlefield",
        "enters the battlefield",
        "play a creature",
        "summon onto the battlefield",
        "put into play",
        "play that card",
        "summon that card",
        "enters the battlefield",
        "enters the battlefield under your control",
        "to the battlefield",
        "place onto the battlefield",
        "invokes onto the battlefield",
        "put a card onto the battlefield",
        "play a permanent",
        "put a creature card into play",
        "create a creature token",
        "create a token"
    ],
    "exile": [
        "remove from the game",
        "exile that card",
        "is exiled",
        "exile enemy creature",
        "exile an artifact",
        "exile a creature",
        "Exile a permanent",
        "Exile a permanent under your control",
        "exile target enemy"
    ],
    "damage": [
        "deal damage",
        "damage",
        "inflict damage",
        "deal damage points",
        "deal damage to enemy creature",
        "inflict damage",
    ],
    "boost card": [
        "it gets +0",
        "it gets +1",
        "it gets +2",
        "it gets +3",
        "it gets +4",
        "it gets +5",
        "it gets +6",
        "creature gains",
        "put a +1/+1 counter on",
        "put a +1/+1 counter on creature",
        "put a +2/+2 counter on",
        "put a +3/+3 counter on",
        "put a +4/+4 counter on",
        "put a +5/+5 counter on",
        "put a +6/+6 counter on",
        "put a +7/+7 counter on",
        "put a +8/+8 counter on",
        "that creature gains haste",
        "that creature gains flying",
        "your creature gains deathtouch",
        "creature gains lifelink",
        "creature gains trample",
        "creature gains haste",
        "creature gains protection from",
        "creature gains attack first",
        "increase power",
        "increase toughness",
    ]
}