initial_effects_object = {
    "gain life": False,
    "lose life": False,
    "draw cards": False,
    "put into play": False,
    "exile": False,
    "damage": False,
    "boost card": False,
}

# Diccionario de frases de referencia adaptadas a Magic: The Gathering
effect_references = {
    "gain life": [
        "gain life",
        "life gain",
        "you gain life",
        "increase your life total",
        "gain 3 life",
        "gain any amount of life"
    ],
    "lose life": [
        "lose life",
        "life loss",
        "you lose life",
        "reduce your life total",
        "lose life",
        "lose 2 life",
        "lose any amount of life"
    ],
    "draw cards": [
        "draw cards",
        "draw a card",
        "draw two cards",
        "draw your hand",
        "card advantage",
        "search your library for a",
        "search your library for a card",
        "search your library for a creature",
        "search your graveyard for a",
        "search your graveyard for a card",
        "search your graveyard for a creature",
        "search your deck for a",
        "search your deck for a card",
        "search your deck for a creature",
        "draw cards",
        "draw a card",
        "draw two cards",
        "card advantage",
        "draw until you have",
        "draw your hand",
        "draw extra cards"
    ],
    "put into play": [
        "put it onto the battlefield",
        "enters the battlefield",
        "play a creature",
        "summon onto the battlefield",
        "put into play",
        "play that card",
        "summon that card",
        "that creature enters the battlefield",
        "that creature enters the battlefield under your control",
        "that enchantment enters the battlefield",
        "that enchantment enters the battlefield under your control",
        "that land enters the battlefield",
        "that land enters the battlefield under your control",
        "that spell enters the battlefield",
        "that spell enters the battlefield under your control",
        "to the battlefield",
        "place onto the battlefield",
        "enters play",
        "comes into play",
        "invokes onto the battlefield",
        "put a card onto the battlefield",
        "play a permanent",
        "put a creature card into play",
    ],
    "exile": [
        "exile",
        "Exile",
        "exiled",
        "remove from the game",
        "exile that card",
        "that card is exiled",
        "exile enemy creature",
        "exile an artifact",
        "exile a creature",
        "Exile a permanent",
        "Exile a permanent you control",
        "Exile a permanent you don't control",
        "Exile a creature",
        "Exile a creature you control",
        "Exile a creature you don't control",
            "exile",
        "exiled",
        "remove from the game",
        "banish",
        "banished",
        "exiled from play",
        "exile target"
    ],
    "damage": [
        "deal damage",
        "damage",
        "inflict damage",
        "takes damage",
        "make 2 damage points",
        "deal 2 damage points",
        "deal 3 damage points",
        "deal 4 damage points",
        "deal 5 damage points",
        "deal 6 damage points",
        "deal damage to enemy creature",
        "inflict damage",
    ],
    "boost card": [
        "boost",
        "boost power",
        "boost toughness",
        "+1",
        "+2",
        "+3",
        "+4",
        "+5",
        "+6",
        "+7",
        "+8",
        "+9",
        "+10",
        "it gets +0",
        "it gets +1",
        "it gets +2",
        "it gets +3",
        "it gets +4",
        "it gets +5",
        "it gets +6",
        "creature gains",
        "put a +1/+1 counter on",
        "put a +1/+1 counter on creature",
        "put a +2/+2 counter on",
        "put a +3/+3 counter on",
        "put a +4/+4 counter on",
        "put a +5/+5 counter on",
        "put a +6/+6 counter on",
        "put a +7/+7 counter on",
        "put a +8/+8 counter on",
        "that creature gains haste",
        "that creature gains flying",
        "your creature gains deathtouch",
        "creature gains lifelink",
        "creature gains trample",
        "creature gains haste",
        "creature gains protection from",
        "creature gains attack first",
        "boost card",
        "pump card",
        "buff card",
        "pump creature",
        "buff creature",
        "increase power",
        "increase toughness",
        "card gets stronger",
        "gets +1/+1",
        "gets pumped",
        "gets buffed",
        "power boost",
        "toughness boost",
        "gains a power bonus",
        "gains a toughness bonus",
        "gets a power/toughness increase"
    ]
}