hearthstone_effect_references = reference_phrases = {
    "Boost/Enhance": [
        "When this attacks, restore #4 Health to the hero of the player who buffed it",
        "(Upgrades when you have 5 Mana",
        "(Upgrades when you have 10 Mana",
        "Will be buffed by Final Showdown",
        "After you upgrade the Tavern, gain +1 Attack for each friendly Dragon"
    ],
    "Draw/Generate": [
        "Deathrattle: Add 3 copies of Arcane Missiles to your hand",
        "Whenever you draw a card, reduce its Cost by (1)",
        "Put a copy of an enemy minion into your hand",
        "Cards you draw from your Hero Power cost (0)",
        "Whenever this minion attacks a hero, add the Coin to your hand"
    ],
    "Discard/Destroy": [
        "Whenever you discard a card, gain +2/+1",
        "When you play or discard this, deal $4 damage to a random enemy",
        "Inspire: Destroy a random minion for each player",
        "Destroy 2 random enemy minions",
        "Discard 2 random cards"
    ],
    "Play/Trigger": [
        "Battlecry: Both players get a random spell",
        "When this attacks, restore #4 Health to the hero of the player who buffed it",
        "When you play or discard this, deal $4 damage to a random enemy",
        "Inspire: Destroy a random minion for each player",
        "Casts When Drawn Summon a 4/4 Nerubian for your opponent"
    ],
    "Summon/Spawn": [
        "Secret: When a friendly minion dies, summon a random minion with the same Cost",
        "Battlecry: If you have a Beast, summon a random Beast",
        "Battlecry and Inspire: Summon a random Legendary minion",
        "Deathrattle: At the end  of the turn, summon a Dreadsteed",
        "Summon a Dreadsteed at the end of the turn"
    ],
    "Transform/Change": [
        "Transform a minion into a 4/2 Boar with Charge",
        "Choose One - Transform into a 2/1 with Charge; or a 3/2 with Stealth",
        "Battlecry: Change all enemy minions' Attack to 1",
        "Attack changed to 1",
        "Transform all minions into 1/1 Sheep"
    ],
    "Control/Manipulate": [
        "Whenever this minion takes damage, also deal that amount to your hero",
        "Choose One - Transform into a 2/1 with Charge; or a 3/2 with Stealth",
        "Stealth",
        "Whenever an enemy minion takes damage, destroy it",
        "Stealth Divine Shield"
    ],
    "Count/Depend": [
        "Secret: When a friendly minion dies, summon a random minion with the same Cost",
        "Battlecry: If you have a Beast, summon a random Beast",
        "Whenever it attacks, restore 4 Health to your hero",
        "When this attacks, restore #4 Health to the hero of the player who buffed it",
        "Whenever you draw a card, reduce its Cost by (1)"
    ]
}



Hearthstone_keywords_data = ['ADJACENT_BUFF',
 'AFFECTED_BY_SPELL_POWER',
 'AI_MUST_PLAY',
 'APPEAR_FUNCTIONALLY_DEAD',
 'AURA',
 'AUTO_ATTACK',
 'AVENGE',
 'BATTLECRY',
 'CANT_ATTACK',
 'CANT_BE_DESTROYED',
 'CANT_BE_FATIGUED',
 'CANT_BE_SILENCED',
 'CANT_BE_TARGETED_BY_HERO_POWERS',
 'CANT_BE_TARGETED_BY_SPELLS',
 'CHARGE',
 'CHOOSE_ONE',
 'COLLECTIONMANAGER_FILTER_MANA_EVEN',
 'COLLECTIONMANAGER_FILTER_MANA_ODD',
 'COLOSSAL',
 'COMBO',
 'CORRUPT',
 'COUNTER',
 'DEATHRATTLE',
 'DEATH_KNIGHT',
 'DISCOVER',
 'DIVINE_SHIELD',
 'DREDGE',
 'DUNGEON_PASSIVE_BUFF',
 'ECHO',
 'ELUSIVE',
 'ENCHANTMENT_INVISIBLE',
 'ENRAGED',
 'EVIL_GLOW',
 'EXCAVATE',
 'FINISH_ATTACK_SPELL_ON_DAMAGE',
 'FORGE',
 'FORGETFUL',
 'FREEZE',
 'FRENZY',
 'GEARS',
 'GHOSTLY',
 'GIGANTIFY',
 'GRIMY_GOONS',
 'HEROPOWER_DAMAGE',
 'HONORABLE_KILL',
 'IGNORE_HIDE_STATS_FOR_BIG_CARD',
 'IMMUNE',
 'INFUSE',
 'INSPIRE',
 'ImmuneToSpellpower',
 'InvisibleDeathrattle',
 'JADE_GOLEM',
 'JADE_LOTUS',
 'KABAL',
 'LIFESTEAL',
 'MAGNETIC',
 'MANATHIRST',
 'MINIATURIZE',
 'MORPH',
 'MULTIPLY_BUFF_VALUE',
 'OUTCAST',
 'OVERHEAL',
 'OVERKILL',
 'OVERLOAD',
 'POISONOUS',
 'PUZZLE',
 'QUEST',
 'QUICKDRAW',
 'REBORN',
 'RECEIVES_DOUBLE_SPELLDAMAGE_BONUS',
 'RUSH',
 'SECRET',
 'SIDE_QUEST',
 'SILENCE',
 'SPARE_PART',
 'SPELLBURST',
 'SPELLPOWER',
 'STARSHIP',
 'STARSHIP_PIECE',
 'START_OF_GAME_KEYWORD',
 'STEALTH',
 'SUMMONED',
 'TAG_ONE_TURN_EFFECT',
 'TAUNT',
 'TITAN',
 'TRADEABLE',
 'TRIGGER_VISUAL',
 'TWINSPELL',
 'UNTOUCHABLE',
 'VENOMOUS',
 'WINDFURY']