MTG_effect_references = {
    "gain life": [
        "gain life",
        "recover life",
        "increase your life total",
    ],
    "lose life": [
        "lose life",
        "lose amount of lives",
        "you lose life",
        "reduce your life total",
        "lose 2 life",
        "lose any amount of life"
    ],
    "draw cards": [
        "draw cards",
        "draw a card",
        "draw your hand",
        "search your library for a",
        "search your graveyard for a",
        "search your deck for a",
        "draw two cards",
        "draw until you have",
    ],
    "put into play": [
        "put it onto the battlefield",
        "enters the battlefield",
        "play a creature",
        "summon onto the battlefield",
        "put into play",
        "play that card",
        "summon that card",
        "enters the battlefield",
        "enters the battlefield under your control",
        "to the battlefield",
        "place onto the battlefield",
        "invokes onto the battlefield",
        "put a card onto the battlefield",
        "play a permanent",
        "put a creature card into play",
        "create a creature token",
        "create a token"
    ],
    "exile": [
        "remove from the game",
        "exile that card",
        "is exiled",
        "exile enemy creature",
        "exile an artifact",
        "exile a creature",
        "Exile a permanent",
        "Exile a permanent under your control",
        "exile target enemy"
    ],
    "damage": [
        "deal damage",
        "damage",
        "inflict damage",
        "deal damage points",
        "deal damage to enemy creature",
        "inflict damage",
    ],
    "boost card": [
        "it gets +0",
        "it gets +1",
        "it gets +2",
        "it gets +3",
        "it gets +4",
        "it gets +5",
        "it gets +6",
        "creature gains",
        "put a +1/+1 counter on",
        "put a +1/+1 counter on creature",
        "put a +2/+2 counter on",
        "put a +3/+3 counter on",
        "put a +4/+4 counter on",
        "put a +5/+5 counter on",
        "put a +6/+6 counter on",
        "put a +7/+7 counter on",
        "put a +8/+8 counter on",
        "that creature gains haste",
        "that creature gains flying",
        "your creature gains deathtouch",
        "creature gains lifelink",
        "creature gains trample",
        "creature gains haste",
        "creature gains protection from",
        "creature gains attack first",
        "increase power",
        "increase toughness",
    ]
}

MTG_keywords_data = [
 'Eerie', 'Battalion', 'Bloodrush', 'Channel', 'Chroma', 'Cohort', 'Constellation', 'Converge', 'Delirium', 'Domain',
 'Fateful hour', 'Ferocious', 'Formidable', 'Grandeur', 'Hellbent', 'Heroic', 'Imprint', 'Inspired', 'Join forces',
 'Kinship', 'Landfall', 'Lieutenant', 'Metalcraft', 'Morbid', 'Parley', 'Radiance', 'Raid', 'Rally', 'Spell mastery',
 'Strive', 'Sweep', 'Tempting offer', 'Threshold', 'Will of the council', 'Adamant', 'Addendum', "Council's dilemma",
 'Eminence', 'Enrage', "Hero's Reward", 'Kinfall', 'Landship', 'Legacy', 'Revolt', 'Underdog', 'Undergrowth', 'Descend',
 'Fathomless descent', 'Magecraft', 'Teamwork', 'Pack tactics', 'Coven', 'Alliance', 'Corrupted', 'Secret council',
 'Celebration', 'Paradox', 'Will of the Planeswalkers', 'Survival', 'Valiant', 'Start your engines!', 'Living weapon',
 'Jump-start', 'Commander ninjutsu', 'Legendary landwalk', 'Nonbasic landwalk', 'Megamorph', 'Haunt', 'Forecast', 'Graft',
 'Fortify', 'Frenzy', 'Gravestorm', 'Hideaway', 'Level Up', 'Infect', 'Reach', 'Rampage', 'Phasing', 'Multikicker', 'Morph',
 'Provoke', 'Modular', 'Ninjutsu', 'Replicate', 'Recover', 'Poisonous', 'Prowl', 'Reinforce', 'Persist', 'Retrace', 'Rebound',
 'Miracle', 'Overload', 'Outlast', 'Prowess', 'Renown', 'Myriad', 'Shroud', 'Trample', 'Vigilance', 'Storm', 'Soulshift',
 'Splice', 'Transmute', 'Ripple', 'Suspend', 'Vanishing', 'Transfigure', 'Wither', 'Undying', 'Soulbond', 'Unleash', 'Ascend',
 'Assist', 'Afterlife', 'Companion', 'Fabricate', 'Embalm', 'Escape', 'Fuse', 'Menace', 'Ingest', 'Melee', 'Improvise', 'Mentor',
 'Partner', 'Mutate', 'Tribute', 'Surge', 'Skulk', 'Undaunted', 'Riot', 'Spectacle', 'Forestwalk', 'Islandwalk', 'Mountainwalk',
 'Double strike', 'Cumulative upkeep', 'First strike', 'Scavenge', 'Encore', 'Deathtouch', 'Defender', 'Amplify', 'Affinity',
 'Bushido', 'Convoke', 'Bloodthirst', 'Absorb', 'Aura Swap', 'Changeling', 'Conspire', 'Cascade', 'Annihilator', 'Battle Cry',
 'Cipher', 'Bestow', 'Dash', 'Awaken', 'Crew', 'Aftermath', 'Afflict', 'Flanking', 'Foretell', 'Fading', 'Eternalize', 'Entwine',
 'Epic', 'Dredge', 'Delve', 'Evoke', 'Exalted', 'Evolve', 'Extort', 'Dethrone', 'Exploit', 'Devoid', 'Emerge', 'Escalate', 'Flying',
 'Haste', 'Hexproof', 'Indestructible', 'Intimidate', 'Lifelink', 'Horsemanship', 'Kicker', 'Madness', 'Swampwalk', 'Desertwalk',
 'Craft', 'Plainswalk', 'Split second', 'Augment', 'Double agenda', 'Reconfigure', 'Ward', 'Partner with', 'Daybound', 'Nightbound',
 'Decayed', 'Disturb', 'Squad', 'Enlist', 'Read Ahead', 'Ravenous', 'Blitz', 'Offering', 'Living metal', 'Backup', 'Banding',
 'Hidden agenda', 'For Mirrodin!', 'Friends forever', 'Casualty', 'Protection', 'Compleated', 'Devour', 'Enchant', 'Flash', 'Boast',
 'Demonstrate', 'Sunburst', 'Flashback', 'Cycling', 'Equip', 'Buyback', 'Hexproof from', 'More Than Meets the Eye', 'Cleave', 'Champion',
 'Specialize', 'Training', 'Prototype', 'Toxic', 'Unearth', 'Intensity', 'Plainscycling', 'Swampcycling', 'Typecycling', 'Wizardcycling',
 'Mountaincycling', 'Basic landcycling', 'Islandcycling', 'Forestcycling', 'Slivercycling', 'Landcycling', 'Bargain', 'Choose a background',
 'Echo', 'Disguise', "Doctor's companion", 'Landwalk', 'Umbra armor', 'Freerunning', 'Spree', 'Saddle', 'Shadow', 'Offspring', 'Impending',
 'Gift', 'Exhaust', 'Max speed', 'Fear', 'Seek', 'Activate', 'Attach', 'Cast', 'Counter', 'Create', 'Destroy', 'Discard', 'Double', 'Exchange',
 'Exile', 'Adapt', 'Support', 'Play', 'Regenerate', 'Reveal', 'Sacrifice', 'Shuffle', 'Tap', 'Untap', 'Vote', 'Time Travel', 'Goad', 'Transform',
 'Surveil', 'Planeswalk', 'Mill', 'Learn', 'Connive', 'Venture into the dungeon', 'Exert', 'Open an Attraction', 'Food', 'Discover', 'Abandon',
 'Explore', 'Treasure', 'Roll to Visit Your Attractions', 'Set in motion', 'Fateseal', 'Manifest', 'Populate', 'Detain', 'Investigate', 'Monstrosity',
 'Clash', 'Scry', 'Incubate', 'Proliferate', 'Meld', 'Convert', 'Fight', 'Bolster', 'Assemble', 'Conjure', 'Amass', 'Cloak', 'Suspect', 'Collect evidence',
 'Role token', 'Plot', 'Heist', 'Forage', 'Manifest dread'
]